project:
  type: website
  output-dir: fundamentals_ml

execute:
  freeze: auto

website:
  title: "Fundamentals of Machine Learning"
  search: true
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home    
      - href: course_schedule.qmd
      - href: about.qmd
    right:
      - icon: github
        href: https://github.com/CBIO-mines/fml-dassault-systems-en
        aria-label: GitHub
  sidebar: 
    logo: assets/mines_paris_psl_logo.png

format:
  html:
    code-link: true
    theme:
      - cosmo
      - brand
      - styles.scss
    toc: true